FROM nginx:alpine

HEALTHCHECK --interval=10s --timeout=2s \
  CMD wget -qO- http://localhost || exit 1
FROM nginx:alpine

HEALTHCHECK --interval=10s --timeout=2s \
  CMD wget -qO- http://localhost || exit 1

